# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 15:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('speed_date', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_number', models.IntegerField(default=None)),
                ('course_title', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Dollars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_2', models.IntegerField()),
                ('interesting_dollars', models.FloatField(default=0.0)),
                ('completeness_dollars', models.FloatField(default=0.0)),
                ('gizmos_dollars', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_number', models.IntegerField(default=None)),
                ('group_name', models.CharField(max_length=30)),
                ('total_dollars', models.FloatField(default=0)),
                ('interesting_dollars', models.FloatField(default=0.0)),
                ('completeness_dollars', models.FloatField(default=0.0)),
                ('gizmos_dollars', models.FloatField(default=0.0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='speed_date.Course')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Courses',
        ),
        migrations.AddField(
            model_name='dollars',
            name='group_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='speed_date.Group'),
        ),
    ]
