# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speed_date', '0002_auto_20160412_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='group_members',
            field=models.CharField(default='', max_length=200),
        ),
    ]
