# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speed_date', '0003_group_group_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='password',
            field=models.CharField(default='', max_length=8),
        ),
    ]
