# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speed_date', '0004_group_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='RotationLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.IntegerField()),
                ('table', models.IntegerField()),
                ('first_team', models.CharField(max_length=30)),
                ('other_team', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='dollars',
            name='group_2',
            field=models.CharField(max_length=30),
        ),
    ]
