# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 00:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('speed_date', '0006_results'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_2', models.CharField(max_length=30)),
                ('notes', models.CharField(max_length=1500)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='speed_date.Group')),
            ],
        ),
    ]
