# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 02:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speed_date', '0007_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='notes',
            field=models.CharField(max_length=5000),
        ),
    ]
