# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speed_date', '0009_results_total_dollars'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='rotation_freeze',
            field=models.BooleanField(default=False),
        ),
    ]
